name: 'Github Information v0.2.5'
description: 'Retrieve Github Information'
inputs:
  github-token:
    description: 'Github Token'
    required: true
  pr-number:
    description: 'Pull Request Number for fetching PR information'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Github Information
      run: |
        echo "Fetching github information"
        chmod +x ${{ github.action_path }}/../../scripts/gh_asset_exec.sh
        ${{ github.action_path }}/../../scripts/gh_asset_exec.sh
      shell: bash
      env:
        STEP_NAME: "github-info"
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_PR_NUMBER: ${{ inputs.pr-number }}
        ACTION_REPO: ${{ github.action_repository }}
        ACTION_VERSION: "v0.2.5"
        GH_TOKEN: ${{ inputs.github-token || github.token }}