name: Frontdoor login v0.2.4
description: Login to Frontdoor and fetch the IBM-Apptio authentication token
inputs:
  github-token:
    description: "GitHub token"
    required: false
  fd-url:
    description: "Frontdoor URL"
    required: true
  fd-public-key:
    description: "Public key for Frontdoor Access"
    required: true
  fd-secret-key:
    description: "Secret key for Frontdoor Access"
    required: true
runs:
  using: "composite"
  steps:
    - name: Frontdoor Login
      shell: bash
      run: |
        echo "Login to Frontdoor"
        chmod +x ${{ github.action_path }}/../../../scripts/gh_asset_exec.sh
        ${{ github.action_path }}/../../../scripts/gh_asset_exec.sh
      env:
        STEP_NAME: "frontdoor-login"
        ACTION_REPO: ${{ github.action_repository }}
        ACTION_VERSION: "v0.2.5"
        GH_TOKEN: ${{ inputs.github-token || github.token }}
        INPUT_FD_URL: ${{ inputs.fd-url }}
        INPUT_FD_PUBLIC_KEY: ${{ inputs.fd-public-key }}
        INPUT_FD_SECRET_KEY: ${{ inputs.fd-secret-key }}
