name: 'Cloudability Metadata v0.2.6'
description: 'Retrieve Cloudability Metadata for a repository deployment'
inputs:
  cloudability-host:
    description: 'Cloudability Host URL for fetching governanve metadata'
    required: true
  fd-env-id:
    description: 'Frontdoor Environment ID for Cloudability Organization'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Cloudability Governance Metadata
      run: |
        echo "Fetching Cloudability Governance metadata"
        chmod +x ${{ github.action_path }}/../../scripts/gh_asset_exec.sh
        ${{ github.action_path }}/../../scripts/gh_asset_exec.sh
      shell: bash
      env:
        STEP_NAME: "metadata"
        INPUT_CLOUDABILITY_HOST: ${{ inputs.cloudability-host }}
        INPUT_FD_ENV_ID: ${{ inputs.fd-env-id }}
        ACTION_VERSION: "v0.2.6"
        GH_TOKEN: ${{ github.token }}